import makeStyles from "@mui/styles/makeStyles";

import theme from "../../config/theme";
import BackGroundImage from "../../../src/assets/svg/background.webp";

const useStyles = makeStyles(
  () => ({
    mainContainer: {
      marginBottom: theme.spacing(16),
    },
    tabIndicator: {
      backgroundColor: "#32AEB6",
    },
    tabContainer: {
      fontSize: 14,
      fontWeight: 400,
      color: theme.palette.text.primary,
      backgroundColor: "#EBF6F6",
      // top: 20,
    },
    selectedTabContainer: {
      "& .css-jpln7h-MuiTabs-scroller": {
        marginTop: 30,
      },

      "& .Mui-selected": {
        fontSize: 14,
        fontWeight: 700,
        // marginTop: 40,
        color: "#32AEB6",
      },
    },
    container: {
      padding: theme.spacing(4),
    },
    descriptionContainer: {
      display: 'flex',
      flexDirection: 'column',
      padding: theme.spacing(4),
    },
    addItemToCart: {
      width: 350,
      fontSize: 16,
      fontWeight: 600,
      textTransform: 'capitalize',
      color: '#32AEB6',
      margin: theme.spacing(2, 6, 3, 6),
      padding: theme.spacing(2, 4),
      backgroundColor: 'white',
      border: 1,
      borderStyle: 'solid',
      borderWidth: 1,
      borderColor: '#32AEB6',
      '&:hover': {
        backgroundColor: 'transparent',
      },
    },
    description: {
      fontSize: 16,
      fontWeight: 600,
      color: theme.palette.text.primary,
    },
    descriptionSummary: {
      fontSize: 16,
      fontWeight: 400,
      fontFamily: 'Nunito',
      paddingTop: theme.spacing(2),
      color: theme.palette.text.secondary,
    },
    boxContainer: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: "#E4EFF0",
      overflow: "hidden",
      marginBottom: 20,
    },
    percentageContainer: {
      display: "flex",
      flexDirection: "row",
      padding: theme.spacing(1.5, 1.5, 1.5, 1.5),
      backgroundColor: "#32AEB6",
      borderRadius: 4,
      strokeWidth: 1,
      flexShrink: 0,
    },
    readInfo: {
      display: "flex",
      flexDirection: "row",
      backgroundColor: "white",
      boxShadow: "0px 12px 24px -4px rgba(145, 158, 171, 0.16)",
      padding: theme.spacing(1, 1.5, 1, 2),
      borderRadius: 4,
      alignItems: "center",
    },
    arrowDownIcon: {
      color: "#10847E",
    },
    percentageInfoContainer: {
      padding: theme.spacing(4, 4, 4, 4),
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    percentOffText: {
      marginLeft: 5,
    },
    productName: {
      fontFamily: "Nunito",
      fontSize: 15,
      fontWeight: 600,
      color: "#1D1D1D",
      marginLeft: 16,
      marginRight: 15,
      letterSpacing: -0.2,
    },
    inStockContainer: {
      display: "flex",
      flexDirection: "row",
      margin: theme.spacing(2, 4, 2, 4),
    },
    inStock: {
      fontFamily: "Nunito",
      fontSize: 15,
      fontWeight: 600,
      color: "#1D1D1D",
      marginLeft: 4,
      // margin: theme.spacing(1, 0, 1, 0),
    },
    price: {
      fontFamily: "Nunito",
      fontSize: 28,
      fontWeight: 600,
      color: "#1D1D1D",
      marginLeft: 16,
      marginTop: 4,
      margin: theme.spacing(1, 0, 1, 0),
    },
    taxes: {
      fontFamily: "Nunito",
      fontSize: 13,
      fontWeight: 400,
      color: "#606060",
      marginLeft: 16,
      margin: theme.spacing(1, 0, 0, 0),
    },
    byIvas: {
      fontFamily: "Nunito",
      fontSize: 13,
      fontWeight: 400,
      color: "#000",
      marginLeft: 16,
      marginTop: 4,
    },
    unit: {
      fontFamily: "Nunito",
      fontSize: 13,
      fontWeight: 400,
      color: "#4F585E",
      marginLeft: 16,
    },
    skuId: {
      fontFamily: "Nunito",
      fontSize: 15,
      fontWeight: 500,
      color: "#1D1D1D",
      marginLeft: 16,
    },
    storeName: {
      fontFamily: "Nunito",
      fontSize: 15,
      fontWeight: 400,
      color: "#1D1D1D",
      marginLeft: 4,
    },
    percentageBorder: {
      backgroundColor: "transparent",
      position: "relative",
      strokeWidth: 1,
      stroke: "black",
      width: 48,
      borderColor: "black",
      height: 32,
    },
    readInfoText: {
      fontFamily: "Nunito",
      fontSize: 13,
      fontWeight: 400,
      color: "#10847E",
    },

    checkoutQuestion: {
      fontFamily: "Nunito",
      fontSize: 13,
      fontWeight: 400,
      color: "#98771D",
      marginLeft: 8,
    },
    knowMoreText: {
      marginTop: 15,
      marginLeft: 8,
      fontFamily: "Nunito",
      fontSize: 17,
      fontWeight: 700,
      color: "#3B4252",
    },
    rightTraingle: {
      borderBottomWidth: 10,
      borderLeftWidth: 10,
      borderBottomColor: "transparent",
      borderTopColor: "transparent",
      borderLeftColor: "#32AEB6",
    },
    questionBox: {
      position: "inherit",
      backgroundColor: "#36384D",
      height: 93,
      margin: theme.spacing(0, 3, 0, 3),
      top: 90,
      borderRadius: 4,
    },
    bottomQuestion: {
      display: "flex",
      flexDirection: "column",
      position: "relative",
      marginBottom: 70,
    },
    knowMoreContainer: {
      paddingTop: 8,
      paddingLeft: 8,
      width: "97%",
      backgroundImage: `url(${BackGroundImage})`,
      backgroundSize: "cover",
      backgroundRepeat: "no-repeat",
      height: 155,
      position: "absolute",
    },
    statusText: {
      fontFamily: "Nunito",
      fontSize: 10,
      fontWeight: 400,
      color: "#FFFFFF",
      width: 25,
      padding: theme.spacing(0.4, 1, 0.4, 1),
      backgroundColor: "#32AEB6",
      borderEndEndRadius: 4,
    },
    footerContainer: {
      display: "flex",
      bottom: 0,
      justifyContent: "space-evenly",
      padding: theme.spacing(3),
      marginLeft: 10,
    },
    scanAgainContainer: {
      backgroundColor: "#FFFFFF",
      borderRadius: 4,
      border: "1px solid #1D1D1D",
      padding: theme.spacing(0, 1, 0, 1),
    },
    addToWishListText: {
      fontFamily: "Nunito",
      fontSize: 16,
      fontWeight: 600,
      color: "#FFFFFF",
      marginLeft: 3,
    },
    similarProductsTextBox: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginLeft: 20,
      marginRight: 20,
    },
    similarProductText: {
      fontFamily: "Nunito",
      fontSize: 16,
      fontWeight: 600,
      color: "#FFFFFF",
    },
    similarProducts: {
      display: 'flex',
      flexDirection: 'row',
      height: 300,
      overflowX: 'scroll'
    },
    addToWishListContainer: {
      backgroundColor: "#1D1D1D",
      marginLeft: 30,
      borderRadius: 4,
    },
    scanAgainText: {
      fontFamily: "Nunito",
      fontSize: 16,
      fontWeight: 600,
      color: "#1D1D1D",
      marginLeft: 5,
    },
    question: {
      fontFamily: "Nunito",
      fontSize: 12,
      fontWeight: 400,
      color: "#FFFFFF",
      margin: theme.spacing(3, 0, 0, 5),
    },
    answer: {
      fontFamily: "Nunito",
      fontSize: 12,
      fontWeight: 400,
      color: "#FFFFFF",
      margin: theme.spacing(-1, 0, 0, 5),
    },
    iconColor: {
      color: "#FFFFFF",
    },
    scanColor: {
      color: "#1D1D1D",
    },
    scrollView: {
      overflowY: "scroll",
    },
    barcodeBtn: {
      height: 48,
      fontSize: 16,
      fontWeight: 600,
      textTransform: 'capitalize',
      flex: 1,
      color: 'black',
      backgroundColor: 'white',
      border: 1,
      borderStyle: 'solid',
      borderWidth: 1,
      borderColor: 'black',
      '&:hover': {
        backgroundColor: 'transparent',
      },
    },
    actionBtn: {
      height: 48,
      fontSize: 16,
      fontWeight: 600,
      textTransform: 'capitalize',
      flex: 1,
      color: theme.palette.IMPrimary.contrastText,
      backgroundColor: 'black',
      '&:hover': {
        backgroundColor: 'black',
      },
    },
    btn: {
      display: 'flex',
      gap: theme.spacing(4),
      bottom: 0,
      alignItems: 'center',
      zIndex: 999,
      position: 'fixed',
      width: "96%",
      textTransform: 'capitalize',
      backgroundColor: "#FFF",
      padding: theme.spacing(4, 2),
      boxShadow: '0px 1px 16px rgba(80, 80, 80, 0.12), 0px 1px 16px rgba(80, 80, 80, 0.12), 0px 1px 16px rgba(80, 80, 80, 0.12)',
    }
  }),
  { name: "productDetailsPage", index: 1 }
);

export default useStyles;
