export enum ModuleUserPermissions {
  PHOENIX_OPERATIONS_HUB = "PHOENIX_OPERATIONS_HUB",
}

export enum UserPermissions {
  INVENTORY_PLANNER = "INVENTORY_PLANNER",
  CLUSTER_MANAGER = "CLUSTER_MANAGER",
}
